name: Basic tests

on:
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Run Tests'



jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install the VPP for testing
      run: |
        curl -s https://packagecloud.io/install/repositories/fdio/master/script.deb.sh | sudo bash
        sudo apt-get install vpp vpp-plugin-core python3-vpp-api
        sudo chmod 777 /dev/shm/global_vm
        sudo chmod 777 /dev/shm/vpe-api
        sudo chmod 777 /run/vpp/*.sock
    - name: Build and test the code
      run: |
        cargo test
    - name: benchmark the client over socket
      run: |
        cargo run --release --example vpp-api-transport-test -- -r 1000 -s /run/vpp/api.sock
    - name: benchmark the client over shared memory
      run: |
        cargo run --release --example vpp-api-transport-test -- -r 1000

