/* Autogenerated data. Do not edit */
#![allow(non_camel_case_types)]
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
use vpp_api_transport::*;
use serde_repr::{Serialize_repr, Deserialize_repr};
#[derive(Debug, Clone, Serialize, Deserialize)] 
union address_union { 
	 ip4 : Ip4Address, 
	 ip6 : Ip6Address, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u32)]
pub enum IfStatusFlags { 
	 IF_STATUS_API_FLAG_ADMIN_UP=1, 
	 IF_STATUS_API_FLAG_LINK_UP=2, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u32)]
pub enum MtuProto { 
	 MTU_PROTO_API_L3=0, 
	 MTU_PROTO_API_IP4=1, 
	 MTU_PROTO_API_IP6=2, 
	 MTU_PROTO_API_MPLS=3, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u32)]
pub enum LinkDuplex { 
	 LINK_DUPLEX_API_UNKNOWN=0, 
	 LINK_DUPLEX_API_HALF=1, 
	 LINK_DUPLEX_API_FULL=2, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u32)]
pub enum SubIfFlags { 
	 SUB_IF_API_FLAG_NO_TAGS=1, 
	 SUB_IF_API_FLAG_ONE_TAG=2, 
	 SUB_IF_API_FLAG_TWO_TAGS=4, 
	 SUB_IF_API_FLAG_DOT1AD=8, 
	 SUB_IF_API_FLAG_EXACT_MATCH=16, 
	 SUB_IF_API_FLAG_DEFAULT=32, 
	 SUB_IF_API_FLAG_OUTER_VLAN_ID_ANY=64, 
	 SUB_IF_API_FLAG_INNER_VLAN_ID_ANY=128, 
	 SUB_IF_API_FLAG_MASK_VNET=254, 
	 SUB_IF_API_FLAG_DOT1AH=256, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u32)]
pub enum RxMode { 
	 RX_MODE_API_UNKNOWN=0, 
	 RX_MODE_API_POLLING=1, 
	 RX_MODE_API_INTERRUPT=2, 
	 RX_MODE_API_ADAPTIVE=3, 
	 RX_MODE_API_DEFAULT=4, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u32)]
pub enum IfType { 
	 IF_API_TYPE_HARDWARE=0, 
	 IF_API_TYPE_SUB=1, 
	 IF_API_TYPE_P2P=2, 
	 IF_API_TYPE_PIPE=3, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u8)]
pub enum Direction { 
	 RX=0, 
	 TX=1, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u8)]
pub enum AddressFamily { 
	 ADDRESS_IP4=0, 
	 ADDRESS_IP6=1, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u8)]
pub enum IpFeatureLocation { 
	 IP_API_FEATURE_INPUT=0, 
	 IP_API_FEATURE_OUTPUT=1, 
	 IP_API_FEATURE_LOCAL=2, 
	 IP_API_FEATURE_PUNT=3, 
	 IP_API_FEATURE_DROP=4, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u8)]
pub enum IpEcn { 
	 IP_API_ECN_NONE=0, 
	 IP_API_ECN_ECT0=1, 
	 IP_API_ECN_ECT1=2, 
	 IP_API_ECN_CE=3, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u8)]
pub enum IpDscp { 
	 IP_API_DSCP_CS0=0, 
	 IP_API_DSCP_CS1=8, 
	 IP_API_DSCP_AF11=10, 
	 IP_API_DSCP_AF12=12, 
	 IP_API_DSCP_AF13=14, 
	 IP_API_DSCP_CS2=16, 
	 IP_API_DSCP_AF21=18, 
	 IP_API_DSCP_AF22=20, 
	 IP_API_DSCP_AF23=22, 
	 IP_API_DSCP_CS3=24, 
	 IP_API_DSCP_AF31=26, 
	 IP_API_DSCP_AF32=28, 
	 IP_API_DSCP_AF33=30, 
	 IP_API_DSCP_CS4=32, 
	 IP_API_DSCP_AF41=34, 
	 IP_API_DSCP_AF42=36, 
	 IP_API_DSCP_AF43=38, 
	 IP_API_DSCP_CS5=40, 
	 IP_API_DSCP_EF=46, 
	 IP_API_DSCP_CS6=48, 
	 IP_API_DSCP_CS7=50, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u8)]
pub enum IpProto { 
	 IP_API_PROTO_HOPOPT=0, 
	 IP_API_PROTO_ICMP=1, 
	 IP_API_PROTO_IGMP=2, 
	 IP_API_PROTO_TCP=6, 
	 IP_API_PROTO_UDP=17, 
	 IP_API_PROTO_GRE=47, 
	 IP_API_PROTO_ESP=50, 
	 IP_API_PROTO_AH=51, 
	 IP_API_PROTO_ICMP6=58, 
	 IP_API_PROTO_EIGRP=88, 
	 IP_API_PROTO_OSPF=89, 
	 IP_API_PROTO_SCTP=132, 
	 IP_API_PROTO_RESERVED=255, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u32)]
pub enum TapFlags { 
	 TAP_API_FLAG_GSO=1, 
	 TAP_API_FLAG_CSUM_OFFLOAD=2, 
	 TAP_API_FLAG_PERSIST=4, 
	 TAP_API_FLAG_ATTACH=8, 
	 TAP_API_FLAG_TUN=16, 
	 TAP_API_FLAG_GRO_COALESCE=32, 
	 TAP_API_FLAG_PACKED=64, 
	 TAP_API_FLAG_IN_ORDER=128, 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct TapCreateV2 { 
	pub client_index : u32, 
	pub context : u32, 
	pub id : u32, 
	pub use_random_mac : bool, 
	pub mac_address : MacAddress, 
	pub num_rx_queues : u8, 
	pub tx_ring_sz : u16, 
	pub rx_ring_sz : u16, 
	pub host_mtu_set : bool, 
	pub host_mtu_size : u32, 
	pub host_mac_addr_set : bool, 
	pub host_mac_addr : MacAddress, 
	pub host_ip4_prefix_set : bool, 
	pub host_ip4_prefix : Ip4AddressWithPrefix, 
	pub host_ip6_prefix_set : bool, 
	pub host_ip6_prefix : Ip6AddressWithPrefix, 
	pub host_ip4_gw_set : bool, 
	pub host_ip4_gw : Ip4Address, 
	pub host_ip6_gw_set : bool, 
	pub host_ip6_gw : Ip6Address, 
	pub tap_flags : TapFlags, 
	pub host_namespace_set : bool, 
	pub host_namespace : FixedSizeString<U64>, 
	pub host_if_name_set : bool, 
	pub host_if_name : FixedSizeString<U64>, 
	pub host_bridge_set : bool, 
	pub host_bridge : FixedSizeString<U64>, 
	pub tag : VariableSizeString, 
} 
impl TapCreateV2 { 
	 pub fn get_message_id() -> String { 
	 	 String::from("tap_create_v2_445835fd") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct TapCreateV2Reply { 
	pub context : u32, 
	pub retval : i32, 
	pub sw_if_index : InterfaceIndex, 
} 
impl TapCreateV2Reply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("tap_create_v2_reply_5383d31f") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct TapDeleteV2 { 
	pub client_index : u32, 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
} 
impl TapDeleteV2 { 
	 pub fn get_message_id() -> String { 
	 	 String::from("tap_delete_v2_f9e6675e") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct TapDeleteV2Reply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl TapDeleteV2Reply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("tap_delete_v2_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct SwInterfaceTapV2Dump { 
	pub client_index : u32, 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
} 
impl SwInterfaceTapV2Dump { 
	 pub fn get_message_id() -> String { 
	 	 String::from("sw_interface_tap_v2_dump_f9e6675e") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct SwInterfaceTapV2Details { 
	pub context : u32, 
	pub sw_if_index : u32, 
	pub id : u32, 
	pub tx_ring_sz : u16, 
	pub rx_ring_sz : u16, 
	pub host_mtu_size : u32, 
	pub host_mac_addr : MacAddress, 
	pub host_ip4_prefix : Ip4AddressWithPrefix, 
	pub host_ip6_prefix : Ip6AddressWithPrefix, 
	pub tap_flags : TapFlags, 
	pub dev_name : FixedSizeString<U64>, 
	pub host_if_name : FixedSizeString<U64>, 
	pub host_namespace : FixedSizeString<U64>, 
	pub host_bridge : FixedSizeString<U64>, 
} 
impl SwInterfaceTapV2Details { 
	 pub fn get_message_id() -> String { 
	 	 String::from("sw_interface_tap_v2_details_e53c16de") 
	 } 
} 
