/* Autogenerated data. Do not edit */
#![allow(non_camel_case_types)]
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
use vpp_api_transport::*;
use serde_repr::{Serialize_repr, Deserialize_repr};
#[derive(Debug, Clone, Serialize, Deserialize)] 
union address_union { 
	 ip4 : Ip4Address, 
	 ip6 : Ip6Address, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u8)]
pub enum AddressFamily { 
	 ADDRESS_IP4=0, 
	 ADDRESS_IP6=1, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u8)]
pub enum IpFeatureLocation { 
	 IP_API_FEATURE_INPUT=0, 
	 IP_API_FEATURE_OUTPUT=1, 
	 IP_API_FEATURE_LOCAL=2, 
	 IP_API_FEATURE_PUNT=3, 
	 IP_API_FEATURE_DROP=4, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u8)]
pub enum IpEcn { 
	 IP_API_ECN_NONE=0, 
	 IP_API_ECN_ECT0=1, 
	 IP_API_ECN_ECT1=2, 
	 IP_API_ECN_CE=3, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u8)]
pub enum IpDscp { 
	 IP_API_DSCP_CS0=0, 
	 IP_API_DSCP_CS1=8, 
	 IP_API_DSCP_AF11=10, 
	 IP_API_DSCP_AF12=12, 
	 IP_API_DSCP_AF13=14, 
	 IP_API_DSCP_CS2=16, 
	 IP_API_DSCP_AF21=18, 
	 IP_API_DSCP_AF22=20, 
	 IP_API_DSCP_AF23=22, 
	 IP_API_DSCP_CS3=24, 
	 IP_API_DSCP_AF31=26, 
	 IP_API_DSCP_AF32=28, 
	 IP_API_DSCP_AF33=30, 
	 IP_API_DSCP_CS4=32, 
	 IP_API_DSCP_AF41=34, 
	 IP_API_DSCP_AF42=36, 
	 IP_API_DSCP_AF43=38, 
	 IP_API_DSCP_CS5=40, 
	 IP_API_DSCP_EF=46, 
	 IP_API_DSCP_CS6=48, 
	 IP_API_DSCP_CS7=50, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u8)]
pub enum IpProto { 
	 IP_API_PROTO_HOPOPT=0, 
	 IP_API_PROTO_ICMP=1, 
	 IP_API_PROTO_IGMP=2, 
	 IP_API_PROTO_TCP=6, 
	 IP_API_PROTO_UDP=17, 
	 IP_API_PROTO_GRE=47, 
	 IP_API_PROTO_ESP=50, 
	 IP_API_PROTO_AH=51, 
	 IP_API_PROTO_ICMP6=58, 
	 IP_API_PROTO_EIGRP=88, 
	 IP_API_PROTO_OSPF=89, 
	 IP_API_PROTO_SCTP=132, 
	 IP_API_PROTO_RESERVED=255, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u8)]
pub enum AclAction { 
	 ACL_ACTION_API_DENY=0, 
	 ACL_ACTION_API_PERMIT=1, 
	 ACL_ACTION_API_PERMIT_REFLECT=2, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u32)]
pub enum IfStatusFlags { 
	 IF_STATUS_API_FLAG_ADMIN_UP=1, 
	 IF_STATUS_API_FLAG_LINK_UP=2, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u32)]
pub enum MtuProto { 
	 MTU_PROTO_API_L3=0, 
	 MTU_PROTO_API_IP4=1, 
	 MTU_PROTO_API_IP6=2, 
	 MTU_PROTO_API_MPLS=3, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u32)]
pub enum LinkDuplex { 
	 LINK_DUPLEX_API_UNKNOWN=0, 
	 LINK_DUPLEX_API_HALF=1, 
	 LINK_DUPLEX_API_FULL=2, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u32)]
pub enum SubIfFlags { 
	 SUB_IF_API_FLAG_NO_TAGS=1, 
	 SUB_IF_API_FLAG_ONE_TAG=2, 
	 SUB_IF_API_FLAG_TWO_TAGS=4, 
	 SUB_IF_API_FLAG_DOT1AD=8, 
	 SUB_IF_API_FLAG_EXACT_MATCH=16, 
	 SUB_IF_API_FLAG_DEFAULT=32, 
	 SUB_IF_API_FLAG_OUTER_VLAN_ID_ANY=64, 
	 SUB_IF_API_FLAG_INNER_VLAN_ID_ANY=128, 
	 SUB_IF_API_FLAG_MASK_VNET=254, 
	 SUB_IF_API_FLAG_DOT1AH=256, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u32)]
pub enum RxMode { 
	 RX_MODE_API_UNKNOWN=0, 
	 RX_MODE_API_POLLING=1, 
	 RX_MODE_API_INTERRUPT=2, 
	 RX_MODE_API_ADAPTIVE=3, 
	 RX_MODE_API_DEFAULT=4, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u32)]
pub enum IfType { 
	 IF_API_TYPE_HARDWARE=0, 
	 IF_API_TYPE_SUB=1, 
	 IF_API_TYPE_P2P=2, 
	 IF_API_TYPE_PIPE=3, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u8)]
pub enum Direction { 
	 RX=0, 
	 TX=1, 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclPluginGetVersion { 
	pub client_index : u32, 
	pub context : u32, 
} 
impl AclPluginGetVersion { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_plugin_get_version_51077d14") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclPluginGetVersionReply { 
	pub context : u32, 
	pub major : u32, 
	pub minor : u32, 
} 
impl AclPluginGetVersionReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_plugin_get_version_reply_9b32cf86") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclPluginControlPing { 
	pub client_index : u32, 
	pub context : u32, 
} 
impl AclPluginControlPing { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_plugin_control_ping_51077d14") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclPluginControlPingReply { 
	pub context : u32, 
	pub retval : i32, 
	pub client_index : u32, 
	pub vpe_pid : u32, 
} 
impl AclPluginControlPingReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_plugin_control_ping_reply_f6b0b8ca") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclPluginGetConnTableMaxEntries { 
	pub client_index : u32, 
	pub context : u32, 
} 
impl AclPluginGetConnTableMaxEntries { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_plugin_get_conn_table_max_entries_51077d14") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclPluginGetConnTableMaxEntriesReply { 
	pub context : u32, 
	pub conn_table_max_entries : u64, 
} 
impl AclPluginGetConnTableMaxEntriesReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_plugin_get_conn_table_max_entries_reply_7a096d3d") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclAddReplace { 
	pub client_index : u32, 
	pub context : u32, 
	pub acl_index : u32, 
	pub tag : FixedSizeString<U64>, 
	pub count : u32, 
	pub r : AclRule, 
} 
impl AclAddReplace { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_add_replace_1cabdeab") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclAddReplaceReply { 
	pub context : u32, 
	pub acl_index : u32, 
	pub retval : i32, 
} 
impl AclAddReplaceReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_add_replace_reply_ac407b0c") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclDel { 
	pub client_index : u32, 
	pub context : u32, 
	pub acl_index : u32, 
} 
impl AclDel { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_del_ef34fea4") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclDelReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl AclDelReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_del_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclInterfaceAddDel { 
	pub client_index : u32, 
	pub context : u32, 
	pub is_add : bool, 
	pub is_input : bool, 
	pub sw_if_index : InterfaceIndex, 
	pub acl_index : u32, 
} 
impl AclInterfaceAddDel { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_interface_add_del_4b54bebd") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclInterfaceAddDelReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl AclInterfaceAddDelReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_interface_add_del_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclInterfaceSetAclList { 
	pub client_index : u32, 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
	pub count : u8, 
	pub n_input : u8, 
	pub acls : u32, 
} 
impl AclInterfaceSetAclList { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_interface_set_acl_list_473982bd") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclInterfaceSetAclListReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl AclInterfaceSetAclListReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_interface_set_acl_list_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclDump { 
	pub client_index : u32, 
	pub context : u32, 
	pub acl_index : u32, 
} 
impl AclDump { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_dump_ef34fea4") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclDetails { 
	pub context : u32, 
	pub acl_index : u32, 
	pub tag : FixedSizeString<U64>, 
	pub count : u32, 
	pub r : AclRule, 
} 
impl AclDetails { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_details_7a97f21c") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclInterfaceListDump { 
	pub client_index : u32, 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
} 
impl AclInterfaceListDump { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_interface_list_dump_f9e6675e") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclInterfaceListDetails { 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
	pub count : u8, 
	pub n_input : u8, 
	pub acls : u32, 
} 
impl AclInterfaceListDetails { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_interface_list_details_e695d256") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MacipAclAdd { 
	pub client_index : u32, 
	pub context : u32, 
	pub tag : FixedSizeString<U64>, 
	pub count : u32, 
	pub r : MacipAclRule, 
} 
impl MacipAclAdd { 
	 pub fn get_message_id() -> String { 
	 	 String::from("macip_acl_add_d648fd0a") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MacipAclAddReply { 
	pub context : u32, 
	pub acl_index : u32, 
	pub retval : i32, 
} 
impl MacipAclAddReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("macip_acl_add_reply_ac407b0c") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MacipAclAddReplace { 
	pub client_index : u32, 
	pub context : u32, 
	pub acl_index : u32, 
	pub tag : FixedSizeString<U64>, 
	pub count : u32, 
	pub r : MacipAclRule, 
} 
impl MacipAclAddReplace { 
	 pub fn get_message_id() -> String { 
	 	 String::from("macip_acl_add_replace_e34402a7") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MacipAclAddReplaceReply { 
	pub context : u32, 
	pub acl_index : u32, 
	pub retval : i32, 
} 
impl MacipAclAddReplaceReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("macip_acl_add_replace_reply_ac407b0c") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MacipAclDel { 
	pub client_index : u32, 
	pub context : u32, 
	pub acl_index : u32, 
} 
impl MacipAclDel { 
	 pub fn get_message_id() -> String { 
	 	 String::from("macip_acl_del_ef34fea4") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MacipAclDelReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl MacipAclDelReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("macip_acl_del_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MacipAclInterfaceAddDel { 
	pub client_index : u32, 
	pub context : u32, 
	pub is_add : bool, 
	pub sw_if_index : InterfaceIndex, 
	pub acl_index : u32, 
} 
impl MacipAclInterfaceAddDel { 
	 pub fn get_message_id() -> String { 
	 	 String::from("macip_acl_interface_add_del_4b8690b1") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MacipAclInterfaceAddDelReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl MacipAclInterfaceAddDelReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("macip_acl_interface_add_del_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MacipAclDump { 
	pub client_index : u32, 
	pub context : u32, 
	pub acl_index : u32, 
} 
impl MacipAclDump { 
	 pub fn get_message_id() -> String { 
	 	 String::from("macip_acl_dump_ef34fea4") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MacipAclDetails { 
	pub context : u32, 
	pub acl_index : u32, 
	pub tag : FixedSizeString<U64>, 
	pub count : u32, 
	pub r : MacipAclRule, 
} 
impl MacipAclDetails { 
	 pub fn get_message_id() -> String { 
	 	 String::from("macip_acl_details_57c7482f") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MacipAclInterfaceGet { 
	pub client_index : u32, 
	pub context : u32, 
} 
impl MacipAclInterfaceGet { 
	 pub fn get_message_id() -> String { 
	 	 String::from("macip_acl_interface_get_51077d14") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MacipAclInterfaceGetReply { 
	pub context : u32, 
	pub count : u32, 
	pub acls : u32, 
} 
impl MacipAclInterfaceGetReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("macip_acl_interface_get_reply_accf9b05") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MacipAclInterfaceListDump { 
	pub client_index : u32, 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
} 
impl MacipAclInterfaceListDump { 
	 pub fn get_message_id() -> String { 
	 	 String::from("macip_acl_interface_list_dump_f9e6675e") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MacipAclInterfaceListDetails { 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
	pub count : u8, 
	pub acls : u32, 
} 
impl MacipAclInterfaceListDetails { 
	 pub fn get_message_id() -> String { 
	 	 String::from("macip_acl_interface_list_details_a0c5d56d") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclInterfaceSetEtypeWhitelist { 
	pub client_index : u32, 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
	pub count : u8, 
	pub n_input : u8, 
	pub whitelist : u16, 
} 
impl AclInterfaceSetEtypeWhitelist { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_interface_set_etype_whitelist_3f5c2d2d") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclInterfaceSetEtypeWhitelistReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl AclInterfaceSetEtypeWhitelistReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_interface_set_etype_whitelist_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclInterfaceEtypeWhitelistDump { 
	pub client_index : u32, 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
} 
impl AclInterfaceEtypeWhitelistDump { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_interface_etype_whitelist_dump_f9e6675e") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclInterfaceEtypeWhitelistDetails { 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
	pub count : u8, 
	pub n_input : u8, 
	pub whitelist : u16, 
} 
impl AclInterfaceEtypeWhitelistDetails { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_interface_etype_whitelist_details_cc2bfded") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclStatsIntfCountersEnable { 
	pub client_index : u32, 
	pub context : u32, 
	pub enable : bool, 
} 
impl AclStatsIntfCountersEnable { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_stats_intf_counters_enable_b3e225d2") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclStatsIntfCountersEnableReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl AclStatsIntfCountersEnableReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("acl_stats_intf_counters_enable_reply_e8d4e804") 
	 } 
} 
