/* Autogenerated data. Do not edit */
#![allow(non_camel_case_types)]
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
use vpp_api_transport::*;
use serde_repr::{Serialize_repr, Deserialize_repr};
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AclRule { 
	pub is_permit : AclAction, 
	pub src_prefix : Prefix, 
	pub dst_prefix : Prefix, 
	pub proto : IpProto, 
	pub srcport_or_icmptype_first : u16, 
	pub srcport_or_icmptype_last : u16, 
	pub dstport_or_icmpcode_first : u16, 
	pub dstport_or_icmpcode_last : u16, 
	pub tcp_flags_mask : u8, 
	pub tcp_flags_value : u8, 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MacipAclRule { 
	pub is_permit : AclAction, 
	pub src_mac : MacAddress, 
	pub src_mac_mask : MacAddress, 
	pub src_prefix : Prefix, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u8)]
pub enum AclAction { 
	 ACL_ACTION_API_DENY=0, 
	 ACL_ACTION_API_PERMIT=1, 
	 ACL_ACTION_API_PERMIT_REFLECT=2, 
} 
