/* Autogenerated data. Do not edit */
#![allow(non_camel_case_types)]
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
use vpp_api_transport::*;
use serde_repr::{Serialize_repr, Deserialize_repr};
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct BuiltinurlEnable { 
	pub client_index : u32, 
	pub context : u32, 
} 
impl BuiltinurlEnable { 
	 pub fn get_message_id() -> String { 
	 	 String::from("builtinurl_enable_51077d14") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct BuiltinurlEnableReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl BuiltinurlEnableReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("builtinurl_enable_reply_e8d4e804") 
	 } 
} 
