/* Autogenerated data. Do not edit */
#![allow(non_camel_case_types)]
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
use vpp_api_transport::*;
use serde_repr::{Serialize_repr, Deserialize_repr};
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct GtpuAddDelTunnel { 
	pub client_index : u32, 
	pub context : u32, 
	pub is_add : bool, 
	pub src_address : Address, 
	pub dst_address : Address, 
	pub mcast_sw_if_index : InterfaceIndex, 
	pub encap_vrf_id : u32, 
	pub decap_next_index : u32, 
	pub teid : u32, 
	pub tteid : u32, 
} 
impl GtpuAddDelTunnel { 
	 pub fn get_message_id() -> String { 
	 	 String::from("gtpu_add_del_tunnel_9a9c0426") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct GtpuAddDelTunnelReply { 
	pub context : u32, 
	pub retval : i32, 
	pub sw_if_index : InterfaceIndex, 
} 
impl GtpuAddDelTunnelReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("gtpu_add_del_tunnel_reply_5383d31f") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct GtpuTunnelUpdateTteid { 
	pub client_index : u32, 
	pub context : u32, 
	pub dst_address : Address, 
	pub encap_vrf_id : u32, 
	pub teid : u32, 
	pub tteid : u32, 
} 
impl GtpuTunnelUpdateTteid { 
	 pub fn get_message_id() -> String { 
	 	 String::from("gtpu_tunnel_update_tteid_8a2db108") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct GtpuTunnelUpdateTteidReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl GtpuTunnelUpdateTteidReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("gtpu_tunnel_update_tteid_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct GtpuTunnelDump { 
	pub client_index : u32, 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
} 
impl GtpuTunnelDump { 
	 pub fn get_message_id() -> String { 
	 	 String::from("gtpu_tunnel_dump_f9e6675e") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct GtpuTunnelDetails { 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
	pub src_address : Address, 
	pub dst_address : Address, 
	pub mcast_sw_if_index : InterfaceIndex, 
	pub encap_vrf_id : u32, 
	pub decap_next_index : u32, 
	pub teid : u32, 
	pub tteid : u32, 
} 
impl GtpuTunnelDetails { 
	 pub fn get_message_id() -> String { 
	 	 String::from("gtpu_tunnel_details_4535cf95") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct SwInterfaceSetGtpuBypass { 
	pub client_index : u32, 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
	pub is_ipv6 : bool, 
	pub enable : bool, 
} 
impl SwInterfaceSetGtpuBypass { 
	 pub fn get_message_id() -> String { 
	 	 String::from("sw_interface_set_gtpu_bypass_65247409") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct SwInterfaceSetGtpuBypassReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl SwInterfaceSetGtpuBypassReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("sw_interface_set_gtpu_bypass_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct GtpuOffloadRx { 
	pub client_index : u32, 
	pub context : u32, 
	pub hw_if_index : u32, 
	pub sw_if_index : u32, 
	pub enable : u8, 
} 
impl GtpuOffloadRx { 
	 pub fn get_message_id() -> String { 
	 	 String::from("gtpu_offload_rx_f0b08786") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct GtpuOffloadRxReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl GtpuOffloadRxReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("gtpu_offload_rx_reply_e8d4e804") 
	 } 
} 
