/* Autogenerated data. Do not edit */
#![allow(non_camel_case_types)]
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
use vpp_api_transport::*;
use serde_repr::{Serialize_repr, Deserialize_repr};
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct VxlanGpeIoamEnable { 
	pub client_index : u32, 
	pub context : u32, 
	pub id : u16, 
	pub trace_ppc : u8, 
	pub pow_enable : bool, 
	pub trace_enable : bool, 
} 
impl VxlanGpeIoamEnable { 
	 pub fn get_message_id() -> String { 
	 	 String::from("vxlan_gpe_ioam_enable_2481bef7") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct VxlanGpeIoamEnableReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl VxlanGpeIoamEnableReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("vxlan_gpe_ioam_enable_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct VxlanGpeIoamDisable { 
	pub client_index : u32, 
	pub context : u32, 
	pub id : u16, 
} 
impl VxlanGpeIoamDisable { 
	 pub fn get_message_id() -> String { 
	 	 String::from("vxlan_gpe_ioam_disable_6b16a45e") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct VxlanGpeIoamDisableReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl VxlanGpeIoamDisableReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("vxlan_gpe_ioam_disable_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct VxlanGpeIoamVniEnable { 
	pub client_index : u32, 
	pub context : u32, 
	pub vni : u32, 
	pub local : Address, 
	pub remote : Address, 
} 
impl VxlanGpeIoamVniEnable { 
	 pub fn get_message_id() -> String { 
	 	 String::from("vxlan_gpe_ioam_vni_enable_997161fb") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct VxlanGpeIoamVniEnableReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl VxlanGpeIoamVniEnableReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("vxlan_gpe_ioam_vni_enable_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct VxlanGpeIoamVniDisable { 
	pub client_index : u32, 
	pub context : u32, 
	pub vni : u32, 
	pub local : Address, 
	pub remote : Address, 
} 
impl VxlanGpeIoamVniDisable { 
	 pub fn get_message_id() -> String { 
	 	 String::from("vxlan_gpe_ioam_vni_disable_997161fb") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct VxlanGpeIoamVniDisableReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl VxlanGpeIoamVniDisableReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("vxlan_gpe_ioam_vni_disable_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct VxlanGpeIoamTransitEnable { 
	pub client_index : u32, 
	pub context : u32, 
	pub outer_fib_index : u32, 
	pub dst_addr : Address, 
} 
impl VxlanGpeIoamTransitEnable { 
	 pub fn get_message_id() -> String { 
	 	 String::from("vxlan_gpe_ioam_transit_enable_553f5b7b") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct VxlanGpeIoamTransitEnableReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl VxlanGpeIoamTransitEnableReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("vxlan_gpe_ioam_transit_enable_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct VxlanGpeIoamTransitDisable { 
	pub client_index : u32, 
	pub context : u32, 
	pub outer_fib_index : u32, 
	pub dst_addr : Address, 
} 
impl VxlanGpeIoamTransitDisable { 
	 pub fn get_message_id() -> String { 
	 	 String::from("vxlan_gpe_ioam_transit_disable_553f5b7b") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct VxlanGpeIoamTransitDisableReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl VxlanGpeIoamTransitDisableReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("vxlan_gpe_ioam_transit_disable_reply_e8d4e804") 
	 } 
} 
