/* Autogenerated data. Do not edit */
#![allow(non_camel_case_types)]
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
use vpp_api_transport::*;
use serde_repr::{Serialize_repr, Deserialize_repr};
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct LldpConfig { 
	pub client_index : u32, 
	pub context : u32, 
	pub tx_hold : u32, 
	pub tx_interval : u32, 
	pub system_name : VariableSizeString, 
} 
impl LldpConfig { 
	 pub fn get_message_id() -> String { 
	 	 String::from("lldp_config_c14445df") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct LldpConfigReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl LldpConfigReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("lldp_config_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct SwInterfaceSetLldp { 
	pub client_index : u32, 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
	pub mgmt_ip4 : Ip4Address, 
	pub mgmt_ip6 : Ip6Address, 
	pub mgmt_oid : u8, 
	pub enable : bool, 
	pub port_desc : VariableSizeString, 
} 
impl SwInterfaceSetLldp { 
	 pub fn get_message_id() -> String { 
	 	 String::from("sw_interface_set_lldp_d646ae0f") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct SwInterfaceSetLldpReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl SwInterfaceSetLldpReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("sw_interface_set_lldp_reply_e8d4e804") 
	 } 
} 
