/* Autogenerated data. Do not edit */
#![allow(non_camel_case_types)]
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
use vpp_api_transport::*;
use serde_repr::{Serialize_repr, Deserialize_repr};
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u32)]
pub enum MemifRole { 
	 MEMIF_ROLE_API_MASTER=0, 
	 MEMIF_ROLE_API_SLAVE=1, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u32)]
pub enum MemifMode { 
	 MEMIF_MODE_API_ETHERNET=0, 
	 MEMIF_MODE_API_IP=1, 
	 MEMIF_MODE_API_PUNT_INJECT=2, 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MemifSocketFilenameAddDel { 
	pub client_index : u32, 
	pub context : u32, 
	pub is_add : bool, 
	pub socket_id : u32, 
	pub socket_filename : FixedSizeString<U108>, 
} 
impl MemifSocketFilenameAddDel { 
	 pub fn get_message_id() -> String { 
	 	 String::from("memif_socket_filename_add_del_a2ce1a10") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MemifSocketFilenameAddDelReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl MemifSocketFilenameAddDelReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("memif_socket_filename_add_del_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MemifCreate { 
	pub client_index : u32, 
	pub context : u32, 
	pub role : MemifRole, 
	pub mode : MemifMode, 
	pub rx_queues : u8, 
	pub tx_queues : u8, 
	pub id : u32, 
	pub socket_id : u32, 
	pub ring_size : u32, 
	pub buffer_size : u16, 
	pub no_zero_copy : bool, 
	pub hw_addr : MacAddress, 
	pub secret : FixedSizeString<U24>, 
} 
impl MemifCreate { 
	 pub fn get_message_id() -> String { 
	 	 String::from("memif_create_b1b25061") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MemifCreateReply { 
	pub context : u32, 
	pub retval : i32, 
	pub sw_if_index : InterfaceIndex, 
} 
impl MemifCreateReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("memif_create_reply_5383d31f") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MemifDelete { 
	pub client_index : u32, 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
} 
impl MemifDelete { 
	 pub fn get_message_id() -> String { 
	 	 String::from("memif_delete_f9e6675e") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MemifDeleteReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl MemifDeleteReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("memif_delete_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MemifSocketFilenameDetails { 
	pub context : u32, 
	pub socket_id : u32, 
	pub socket_filename : FixedSizeString<U108>, 
} 
impl MemifSocketFilenameDetails { 
	 pub fn get_message_id() -> String { 
	 	 String::from("memif_socket_filename_details_7ff326f7") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MemifSocketFilenameDump { 
	pub client_index : u32, 
	pub context : u32, 
} 
impl MemifSocketFilenameDump { 
	 pub fn get_message_id() -> String { 
	 	 String::from("memif_socket_filename_dump_51077d14") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MemifDetails { 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
	pub hw_addr : MacAddress, 
	pub id : u32, 
	pub role : MemifRole, 
	pub mode : MemifMode, 
	pub zero_copy : bool, 
	pub socket_id : u32, 
	pub ring_size : u32, 
	pub buffer_size : u16, 
	pub flags : IfStatusFlags, 
	pub if_name : FixedSizeString<U64>, 
} 
impl MemifDetails { 
	 pub fn get_message_id() -> String { 
	 	 String::from("memif_details_d0382c4c") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct MemifDump { 
	pub client_index : u32, 
	pub context : u32, 
} 
impl MemifDump { 
	 pub fn get_message_id() -> String { 
	 	 String::from("memif_dump_51077d14") 
	 } 
} 
