/* Autogenerated data. Do not edit */
#![allow(non_camel_case_types)]
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
use vpp_api_transport::*;
use serde_repr::{Serialize_repr, Deserialize_repr};
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct SvsPluginGetVersion { 
	pub client_index : u32, 
	pub context : u32, 
} 
impl SvsPluginGetVersion { 
	 pub fn get_message_id() -> String { 
	 	 String::from("svs_plugin_get_version_51077d14") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct SvsPluginGetVersionReply { 
	pub context : u32, 
	pub major : u32, 
	pub minor : u32, 
} 
impl SvsPluginGetVersionReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("svs_plugin_get_version_reply_9b32cf86") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct SvsTableAddDel { 
	pub client_index : u32, 
	pub context : u32, 
	pub is_add : bool, 
	pub af : AddressFamily, 
	pub table_id : u32, 
} 
impl SvsTableAddDel { 
	 pub fn get_message_id() -> String { 
	 	 String::from("svs_table_add_del_7d21cb2a") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct SvsTableAddDelReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl SvsTableAddDelReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("svs_table_add_del_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct SvsRouteAddDel { 
	pub client_index : u32, 
	pub context : u32, 
	pub is_add : bool, 
	pub prefix : Prefix, 
	pub table_id : u32, 
	pub source_table_id : u32, 
} 
impl SvsRouteAddDel { 
	 pub fn get_message_id() -> String { 
	 	 String::from("svs_route_add_del_d39e31fc") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct SvsRouteAddDelReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl SvsRouteAddDelReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("svs_route_add_del_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct SvsEnableDisable { 
	pub client_index : u32, 
	pub context : u32, 
	pub is_enable : bool, 
	pub af : AddressFamily, 
	pub table_id : u32, 
	pub sw_if_index : InterfaceIndex, 
} 
impl SvsEnableDisable { 
	 pub fn get_message_id() -> String { 
	 	 String::from("svs_enable_disable_634b89d2") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct SvsEnableDisableReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl SvsEnableDisableReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("svs_enable_disable_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct SvsDump { 
	pub client_index : u32, 
	pub context : u32, 
} 
impl SvsDump { 
	 pub fn get_message_id() -> String { 
	 	 String::from("svs_dump_51077d14") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct SvsDetails { 
	pub context : u32, 
	pub table_id : u32, 
	pub sw_if_index : InterfaceIndex, 
	pub af : AddressFamily, 
} 
impl SvsDetails { 
	 pub fn get_message_id() -> String { 
	 	 String::from("svs_details_b8523d64") 
	 } 
} 
