/* Autogenerated data. Do not edit */
#![allow(non_camel_case_types)]
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
use vpp_api_transport::*;
use serde_repr::{Serialize_repr, Deserialize_repr};
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct WireguardInterface { 
	pub user_instance : u32, 
	pub sw_if_index : InterfaceIndex, 
	pub private_key : u8, 
	pub public_key : u8, 
	pub port : u16, 
	pub src_ip : Address, 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct WireguardPeer { 
	pub public_key : u8, 
	pub port : u16, 
	pub persistent_keepalive : u16, 
	pub table_id : u32, 
	pub endpoint : Address, 
	pub sw_if_index : InterfaceIndex, 
	pub flags : WireguardPeerFlags, 
	pub n_allowed_ips : u8, 
	pub allowed_ips : Prefix, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u8)]
pub enum WireguardPeerFlags { 
	 WIREGUARD_PEER_STATUS_DEAD=1, 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct WireguardInterfaceCreate { 
	pub client_index : u32, 
	pub context : u32, 
	pub interface : WireguardInterface, 
	pub generate_key : bool, 
} 
impl WireguardInterfaceCreate { 
	 pub fn get_message_id() -> String { 
	 	 String::from("wireguard_interface_create_a530137e") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct WireguardInterfaceCreateReply { 
	pub context : u32, 
	pub retval : i32, 
	pub sw_if_index : InterfaceIndex, 
} 
impl WireguardInterfaceCreateReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("wireguard_interface_create_reply_5383d31f") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct WireguardInterfaceDelete { 
	pub client_index : u32, 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
} 
impl WireguardInterfaceDelete { 
	 pub fn get_message_id() -> String { 
	 	 String::from("wireguard_interface_delete_f9e6675e") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct WireguardInterfaceDeleteReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl WireguardInterfaceDeleteReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("wireguard_interface_delete_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct WireguardInterfaceDump { 
	pub client_index : u32, 
	pub context : u32, 
	pub show_private_key : bool, 
	pub sw_if_index : InterfaceIndex, 
} 
impl WireguardInterfaceDump { 
	 pub fn get_message_id() -> String { 
	 	 String::from("wireguard_interface_dump_2c954158") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct WireguardInterfaceDetails { 
	pub context : u32, 
	pub interface : WireguardInterface, 
} 
impl WireguardInterfaceDetails { 
	 pub fn get_message_id() -> String { 
	 	 String::from("wireguard_interface_details_0dd4865d") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct WireguardPeerAdd { 
	pub client_index : u32, 
	pub context : u32, 
	pub peer : WireguardPeer, 
} 
impl WireguardPeerAdd { 
	 pub fn get_message_id() -> String { 
	 	 String::from("wireguard_peer_add_ed792326") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct WireguardPeerAddReply { 
	pub context : u32, 
	pub retval : i32, 
	pub peer_index : u32, 
} 
impl WireguardPeerAddReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("wireguard_peer_add_reply_084a0cd3") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct WireguardPeerRemove { 
	pub client_index : u32, 
	pub context : u32, 
	pub peer_index : u32, 
} 
impl WireguardPeerRemove { 
	 pub fn get_message_id() -> String { 
	 	 String::from("wireguard_peer_remove_3b74607a") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct WireguardPeerRemoveReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl WireguardPeerRemoveReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("wireguard_peer_remove_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct WireguardPeersDump { 
	pub client_index : u32, 
	pub context : u32, 
} 
impl WireguardPeersDump { 
	 pub fn get_message_id() -> String { 
	 	 String::from("wireguard_peers_dump_51077d14") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct WireguardPeersDetails { 
	pub context : u32, 
	pub peer : WireguardPeer, 
} 
impl WireguardPeersDetails { 
	 pub fn get_message_id() -> String { 
	 	 String::from("wireguard_peers_details_2097f740") 
	 } 
} 
