/* Autogenerated data. Do not edit */
#![allow(non_camel_case_types)]
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
use vpp_api_transport::*;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum::{U10, U24, U256, U32, U64};
use crate::ip_types::*; 
use crate::fib_types::*; 
use crate::ip_types::*; 
use crate::interface_types::*; 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AbfPolicy { 
	pub policy_id : u32, 
	pub acl_index : u32, 
	pub n_paths : u8, 
	pub paths : FibPath, 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AbfItfAttach { 
	pub policy_id : u32, 
	pub sw_if_index : InterfaceIndex, 
	pub priority : u32, 
	pub is_ipv6 : bool, 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AbfPluginGetVersion { 
	pub client_index : u32, 
	pub context : u32, 
} 
impl AbfPluginGetVersion { 
	 pub fn get_message_name_and_crc() -> String { 
	 	 String::from("abf_plugin_get_version_51077d14") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AbfPluginGetVersionReply { 
	pub context : u32, 
	pub major : u32, 
	pub minor : u32, 
} 
impl AbfPluginGetVersionReply { 
	 pub fn get_message_name_and_crc() -> String { 
	 	 String::from("abf_plugin_get_version_reply_9b32cf86") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AbfPolicyAddDel { 
	pub client_index : u32, 
	pub context : u32, 
	pub is_add : bool, 
	pub policy : AbfPolicy, 
} 
impl AbfPolicyAddDel { 
	 pub fn get_message_name_and_crc() -> String { 
	 	 String::from("abf_policy_add_del_ee66f93e") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AbfPolicyAddDelReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl AbfPolicyAddDelReply { 
	 pub fn get_message_name_and_crc() -> String { 
	 	 String::from("abf_policy_add_del_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AbfPolicyDetails { 
	pub context : u32, 
	pub policy : AbfPolicy, 
} 
impl AbfPolicyDetails { 
	 pub fn get_message_name_and_crc() -> String { 
	 	 String::from("abf_policy_details_6769e504") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AbfPolicyDump { 
	pub client_index : u32, 
	pub context : u32, 
} 
impl AbfPolicyDump { 
	 pub fn get_message_name_and_crc() -> String { 
	 	 String::from("abf_policy_dump_51077d14") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AbfItfAttachAddDel { 
	pub client_index : u32, 
	pub context : u32, 
	pub is_add : bool, 
	pub attach : AbfItfAttach, 
} 
impl AbfItfAttachAddDel { 
	 pub fn get_message_name_and_crc() -> String { 
	 	 String::from("abf_itf_attach_add_del_25c8621b") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AbfItfAttachAddDelReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl AbfItfAttachAddDelReply { 
	 pub fn get_message_name_and_crc() -> String { 
	 	 String::from("abf_itf_attach_add_del_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AbfItfAttachDetails { 
	pub context : u32, 
	pub attach : AbfItfAttach, 
} 
impl AbfItfAttachDetails { 
	 pub fn get_message_name_and_crc() -> String { 
	 	 String::from("abf_itf_attach_details_7819523e") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AbfItfAttachDump { 
	pub client_index : u32, 
	pub context : u32, 
} 
impl AbfItfAttachDump { 
	 pub fn get_message_name_and_crc() -> String { 
	 	 String::from("abf_itf_attach_dump_51077d14") 
	 } 
} 
