/*
   Autogenerated Data, Do not Edit! 
   Author: @felixfaisal 
*/
#![allow(non_camel_case_types)]
use vpp_macros::Message; 
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
use vpp_api_transport::*;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum::{U10, U24, U256, U32, U64};
use crate::ip_types::*; 
use crate::fib_types::*; 
use crate::ip_types::*; 
use crate::interface_types::*; 
// Implementation for abf_policy 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AbfPolicy { 
	pub policy_id : u32, 
	pub acl_index : u32, 
	pub n_paths : u8, 
	pub paths : FibPath, 
} 
// Implementation for abf_itf_attach 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct AbfItfAttach { 
	pub policy_id : u32, 
	pub sw_if_index : InterfaceIndex, 
	pub priority : u32, 
	pub is_ipv6 : bool, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(abf_plugin_get_version_51077d14)] 
pub struct AbfPluginGetVersion { 
	pub client_index : u32, 
	pub context : u32, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(abf_plugin_get_version_reply_9b32cf86)] 
pub struct AbfPluginGetVersionReply { 
	pub context : u32, 
	pub major : u32, 
	pub minor : u32, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(abf_policy_add_del_ee66f93e)] 
pub struct AbfPolicyAddDel { 
	pub client_index : u32, 
	pub context : u32, 
	pub is_add : bool, 
	pub policy : AbfPolicy, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(abf_policy_add_del_reply_e8d4e804)] 
pub struct AbfPolicyAddDelReply { 
	pub context : u32, 
	pub retval : i32, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(abf_policy_details_6769e504)] 
pub struct AbfPolicyDetails { 
	pub context : u32, 
	pub policy : AbfPolicy, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(abf_policy_dump_51077d14)] 
pub struct AbfPolicyDump { 
	pub client_index : u32, 
	pub context : u32, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(abf_itf_attach_add_del_25c8621b)] 
pub struct AbfItfAttachAddDel { 
	pub client_index : u32, 
	pub context : u32, 
	pub is_add : bool, 
	pub attach : AbfItfAttach, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(abf_itf_attach_add_del_reply_e8d4e804)] 
pub struct AbfItfAttachAddDelReply { 
	pub context : u32, 
	pub retval : i32, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(abf_itf_attach_details_7819523e)] 
pub struct AbfItfAttachDetails { 
	pub context : u32, 
	pub attach : AbfItfAttach, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(abf_itf_attach_dump_51077d14)] 
pub struct AbfItfAttachDump { 
	pub client_index : u32, 
	pub context : u32, 
} 
