/*
   Autogenerated Data, Do not Edit! 
   Author: @felixfaisal 
*/
#![allow(non_camel_case_types)]
use vpp_macros::Message; 
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
use vpp_api_transport::*;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum::{U10, U24, U256, U32, U64};
use crate::ip_types::*; 
use crate::ethernet_types::*; 
use crate::interface_types::*; 
// Implementation for proxy_arp 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct ProxyArp { 
	pub table_id : u32, 
	pub low : Ip4Address, 
	pub hi : Ip4Address, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(proxy_arp_add_del_85486cbd)] 
pub struct ProxyArpAddDel { 
	pub client_index : u32, 
	pub context : u32, 
	pub is_add : bool, 
	pub proxy : ProxyArp, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(proxy_arp_add_del_reply_e8d4e804)] 
pub struct ProxyArpAddDelReply { 
	pub context : u32, 
	pub retval : i32, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(proxy_arp_dump_51077d14)] 
pub struct ProxyArpDump { 
	pub client_index : u32, 
	pub context : u32, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(proxy_arp_details_9228c150)] 
pub struct ProxyArpDetails { 
	pub context : u32, 
	pub proxy : ProxyArp, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(proxy_arp_intfc_enable_disable_ae6cfcfb)] 
pub struct ProxyArpIntfcEnableDisable { 
	pub client_index : u32, 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
	pub enable : bool, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(proxy_arp_intfc_enable_disable_reply_e8d4e804)] 
pub struct ProxyArpIntfcEnableDisableReply { 
	pub context : u32, 
	pub retval : i32, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(proxy_arp_intfc_dump_51077d14)] 
pub struct ProxyArpIntfcDump { 
	pub client_index : u32, 
	pub context : u32, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(proxy_arp_intfc_details_f6458e5f)] 
pub struct ProxyArpIntfcDetails { 
	pub context : u32, 
	pub sw_if_index : u32, 
} 
