/* Autogenerated data. Do not edit */
#![allow(non_camel_case_types)]
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
use vpp_api_transport::*;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum::{U10, U24, U256, U32, U64};
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct CdpEnableDisable { 
	pub client_index : u32, 
	pub context : u32, 
	pub enable_disable : bool, 
} 
impl CdpEnableDisable { 
	 pub fn get_message_id() -> String { 
	 	 String::from("cdp_enable_disable_2e7b47df") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct CdpEnableDisableReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl CdpEnableDisableReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("cdp_enable_disable_reply_e8d4e804") 
	 } 
} 
