/* Autogenerated data. Do not edit */
#![allow(non_camel_case_types)]
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
use vpp_api_transport::*;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum::{U10, U24, U256, U32, U64};
use crate::interface_types::*; 
use crate::ip_types::*; 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct Dhcp6PdClientEnableDisable { 
	pub client_index : u32, 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
	pub prefix_group : FixedSizeString<U64>, 
	pub enable : bool, 
} 
impl Dhcp6PdClientEnableDisable { 
	 pub fn get_message_id() -> String { 
	 	 String::from("dhcp6_pd_client_enable_disable_a75a0772") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct Dhcp6PdClientEnableDisableReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl Dhcp6PdClientEnableDisableReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("dhcp6_pd_client_enable_disable_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct Ip6AddDelAddressUsingPrefix { 
	pub client_index : u32, 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
	pub prefix_group : FixedSizeString<U64>, 
	pub address_with_prefix : Ip6AddressWithPrefix, 
	pub is_add : bool, 
} 
impl Ip6AddDelAddressUsingPrefix { 
	 pub fn get_message_id() -> String { 
	 	 String::from("ip6_add_del_address_using_prefix_9b3d11e0") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct Ip6AddDelAddressUsingPrefixReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl Ip6AddDelAddressUsingPrefixReply { 
	 pub fn get_message_id() -> String { 
	 	 String::from("ip6_add_del_address_using_prefix_reply_e8d4e804") 
	 } 
} 
