/*
   Autogenerated Data, Do not Edit! 
   Author: @felixfaisal 
*/
#![allow(non_camel_case_types)]
use vpp_macros::Message; 
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
use vpp_api_transport::*;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum::{U10, U24, U256, U32, U64};
use crate::ip_types::*; 
use crate::interface_types::*; 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(dslite_add_del_pool_addr_range_c448457a)] 
pub struct DsliteAddDelPoolAddrRange { 
	pub client_index : u32, 
	pub context : u32, 
	pub start_addr : Ip4Address, 
	pub end_addr : Ip4Address, 
	pub is_add : bool, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(dslite_add_del_pool_addr_range_reply_e8d4e804)] 
pub struct DsliteAddDelPoolAddrRangeReply { 
	pub context : u32, 
	pub retval : i32, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(dslite_address_dump_51077d14)] 
pub struct DsliteAddressDump { 
	pub client_index : u32, 
	pub context : u32, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(dslite_address_details_ec26d648)] 
pub struct DsliteAddressDetails { 
	pub context : u32, 
	pub ip_address : Ip4Address, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(dslite_set_aftr_addr_1e955f8d)] 
pub struct DsliteSetAftrAddr { 
	pub client_index : u32, 
	pub context : u32, 
	pub ip4_addr : Ip4Address, 
	pub ip6_addr : Ip6Address, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(dslite_set_aftr_addr_reply_e8d4e804)] 
pub struct DsliteSetAftrAddrReply { 
	pub context : u32, 
	pub retval : i32, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(dslite_get_aftr_addr_51077d14)] 
pub struct DsliteGetAftrAddr { 
	pub client_index : u32, 
	pub context : u32, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(dslite_get_aftr_addr_reply_38e30db1)] 
pub struct DsliteGetAftrAddrReply { 
	pub context : u32, 
	pub retval : i32, 
	pub ip4_addr : Ip4Address, 
	pub ip6_addr : Ip6Address, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(dslite_set_b4_addr_1e955f8d)] 
pub struct DsliteSetB4Addr { 
	pub client_index : u32, 
	pub context : u32, 
	pub ip4_addr : Ip4Address, 
	pub ip6_addr : Ip6Address, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(dslite_set_b4_addr_reply_e8d4e804)] 
pub struct DsliteSetB4AddrReply { 
	pub context : u32, 
	pub retval : i32, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(dslite_get_b4_addr_51077d14)] 
pub struct DsliteGetB4Addr { 
	pub client_index : u32, 
	pub context : u32, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(dslite_get_b4_addr_reply_38e30db1)] 
pub struct DsliteGetB4AddrReply { 
	pub context : u32, 
	pub retval : i32, 
	pub ip4_addr : Ip4Address, 
	pub ip6_addr : Ip6Address, 
} 
