/*
   Autogenerated Data, Do not Edit! 
   Author: @felixfaisal 
*/
#![allow(non_camel_case_types)]
use vpp_macros::Message; 
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
use vpp_api_transport::*;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum::{U10, U24, U256, U32, U64};
use crate::interface_types::*; 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(pipe_create_bb263bd3)] 
pub struct PipeCreate { 
	pub client_index : u32, 
	pub context : u32, 
	pub is_specified : bool, 
	pub user_instance : u32, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(pipe_create_reply_d4c2c2b3)] 
pub struct PipeCreateReply { 
	pub context : u32, 
	pub retval : i32, 
	pub sw_if_index : InterfaceIndex, 
	pub pipe_sw_if_index : InterfaceIndex, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(pipe_delete_f9e6675e)] 
pub struct PipeDelete { 
	pub client_index : u32, 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(pipe_delete_reply_e8d4e804)] 
pub struct PipeDeleteReply { 
	pub context : u32, 
	pub retval : i32, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(pipe_dump_51077d14)] 
pub struct PipeDump { 
	pub client_index : u32, 
	pub context : u32, 
} 
#[derive(Debug, Clone, Serialize, Deserialize, Message)] 
#[message_name_and_crc(pipe_details_43ac107a)] 
pub struct PipeDetails { 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
	pub pipe_sw_if_index : InterfaceIndex, 
	pub instance : u32, 
} 
