/* Autogenerated data. Do not edit */
#![allow(non_camel_case_types)]
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
use vpp_api_transport::*;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum::{U10, U24, U256, U32, U64};
use crate::interface_types::*; 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct PipeCreate { 
	pub client_index : u32, 
	pub context : u32, 
	pub is_specified : bool, 
	pub user_instance : u32, 
} 
impl PipeCreate { 
	 pub fn get_message_name_and_crc() -> String { 
	 	 String::from("pipe_create_bb263bd3") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct PipeCreateReply { 
	pub context : u32, 
	pub retval : i32, 
	pub sw_if_index : InterfaceIndex, 
	pub pipe_sw_if_index : InterfaceIndex, 
} 
impl PipeCreateReply { 
	 pub fn get_message_name_and_crc() -> String { 
	 	 String::from("pipe_create_reply_d4c2c2b3") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct PipeDelete { 
	pub client_index : u32, 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
} 
impl PipeDelete { 
	 pub fn get_message_name_and_crc() -> String { 
	 	 String::from("pipe_delete_f9e6675e") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct PipeDeleteReply { 
	pub context : u32, 
	pub retval : i32, 
} 
impl PipeDeleteReply { 
	 pub fn get_message_name_and_crc() -> String { 
	 	 String::from("pipe_delete_reply_e8d4e804") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct PipeDump { 
	pub client_index : u32, 
	pub context : u32, 
} 
impl PipeDump { 
	 pub fn get_message_name_and_crc() -> String { 
	 	 String::from("pipe_dump_51077d14") 
	 } 
} 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct PipeDetails { 
	pub context : u32, 
	pub sw_if_index : InterfaceIndex, 
	pub pipe_sw_if_index : InterfaceIndex, 
	pub instance : u32, 
} 
impl PipeDetails { 
	 pub fn get_message_name_and_crc() -> String { 
	 	 String::from("pipe_details_43ac107a") 
	 } 
} 
