/*
   Autogenerated Data, Do not Edit! 
   Author: @felixfaisal 
*/
#![allow(non_camel_case_types)]
use vpp_macros::Message; 
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
use vpp_api_transport::*;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum::{U10, U24, U256, U32, U64};
use crate::interface_types::*; 
use crate::ip_types::*; 
// Implementation for tunnel 
#[derive(Debug, Clone, Serialize, Deserialize)] 
pub struct Tunnel { 
	pub instance : u32, 
	pub src : Address, 
	pub dst : Address, 
	pub sw_if_index : InterfaceIndex, 
	pub table_id : u32, 
	pub encap_decap_flags : TunnelEncapDecapFlags, 
	pub mode : TunnelMode, 
	pub flags : TunnelFlags, 
	pub dscp : IpDscp, 
	pub hop_limit : u8, 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u8)]
pub enum TunnelEncapDecapFlags { 
	 TUNNEL_API_ENCAP_DECAP_FLAG_NONE=0, 
	 TUNNEL_API_ENCAP_DECAP_FLAG_ENCAP_COPY_DF=1, 
	 TUNNEL_API_ENCAP_DECAP_FLAG_ENCAP_SET_DF=2, 
	 TUNNEL_API_ENCAP_DECAP_FLAG_ENCAP_COPY_DSCP=4, 
	 TUNNEL_API_ENCAP_DECAP_FLAG_ENCAP_COPY_ECN=8, 
	 TUNNEL_API_ENCAP_DECAP_FLAG_DECAP_COPY_ECN=16, 
	 TUNNEL_API_ENCAP_DECAP_FLAG_ENCAP_INNER_HASH=32, 
	 TUNNEL_API_ENCAP_DECAP_FLAG_ENCAP_COPY_HOP_LIMIT=64, 
	 TUNNEL_API_ENCAP_DECAP_FLAG_ENCAP_COPY_FLOW_LABEL=128, 
	 #[serde(other)] 
	 Invalid 
} 
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)] 
#[repr(u8)]
pub enum TunnelMode { 
	 TUNNEL_API_MODE_P2P=0, 
	 TUNNEL_API_MODE_MP=1, 
	 #[serde(other)] 
	 Invalid 
} 
