name: Basic tests

on:
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Run Tests'



jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install and start VPP
      run: |
        curl -s https://packagecloud.io/install/repositories/fdio/master/script.deb.sh | sudo bash
        sudo apt-get install vpp libvppinfra libvppinfra-dev vpp-plugin-core vpp-plugin-dpdk python3-vpp-api vpp-dbg vpp-dev vpp-plugin-devtools
        echo "#"  | sudo tee -a /etc/vpp/startup.conf
        echo "plugins { plugin dpdk_plugin.so { disable } }" | sudo tee -a /etc/vpp/startup.conf
        echo "#" | sudo tee -a /etc/vpp/startup.conf
        sudo service vpp stop
        sudo service vpp start
        echo "Sleeping for 10 sec"
        sleep 10
        echo "Changing permissions and testing that VPP is alive"
        sudo chmod o+w /run/vpp/api.sock
        sudo chmod o+w /run/vpp/cli.sock
        vppctl show version
    - name: Find libvppapiclient.so and print its location for checking
      run: |
        sudo find / -name libvppapiclient.so -print
    - name: Install build prerequisites
      run: |
        sudo apt-get install -y build-essential clang
    - name: Build and test the code
      run: |
        cargo test
    - name: benchmark the client over socket
      run: |
        cargo run --release --example vpp-api-transport-test -- -r 1000 -s /run/vpp/api.sock
    - name: benchmark the client over shared memory
      run: |
        cargo run --release --example vpp-api-transport-test -- -r 1000
    - name: Create a test package using vpp-api-gen
      run: |
        pwd
        ls -al ..
        cargo run -- --in-file /usr/share/vpp/api/ --parse-type Tree --create-package --package-name testvpp --vppapi-opts '{ path = "../vpp-api/{crate}/" }'
        echo "Finished creating the test package"
    - name: Run tests within the generated package
      run: |
        cd ../testvpp
        echo '==== Cargo.toml ===='
        cat Cargo.toml
        echo '==== end ===='
        pwd

        cargo test -- --test-threads 1
